### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by kraileth**
Just a few readme improvements.

BTW: The EDE project here on GH is missing the "issues" functionality! I guess the intention to disable it was to keep using the project's bug tracker? Given today's development practices (and the fact that Github makes things really easy for "drive-by contributors" or people new to open source), it might make sense to re-think this. It would be nice if opening issues could be added so that problems can be reported by GH users, too.

### CODE REVIEW

**Comment by sanel** [comment]
Hi @kraileth and thanks for commenting. Ideas are good and make sense - I just need to figure out how to keep existing bugs in bugzilla (which needs my focus to migrate it) and newly reported bugs here on github.

**Comment by kraileth** [comment]
Great! Let me know if I can help with anything (e.g. migrating the project wiki over to GH in case that's desirable - but perhaps we should discuss things like that via mail again).

Oh, and just curious: What's wrong with the proposed readme improvements?

**Comment by sanel** [comment]
What proposed readme improvements? Sorry, I'm jumping in from other tasks and looks like I missed something :)

**Comment by sanel** [comment]
Ok, my bad - didn't noticed your changes :) Merging it right now.

Thanks!!

**Comment by sanel** [comment]
Can you please make yet another pull request? Github doesn't allows me to merge your code and automatically marked PR as closed, presumably after you removed your branch, I guess.

**Pull request merged**
